    - name: Python | install python-pip
      apt: name=python-pip update_cache=yes state=latest
      sudo: yes
      tags: 
        -setup      
        -python 

    - name: Python | Update pip
      shell: pip install -U pip
      sudo: yes
      tags: 
        -setup      
        -python 

