
FROM ubuntu:16.04

# Install Ansible
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y software-properties-common git python-dev wget
RUN apt-get install -y python-pip
RUN pip install -U pip
RUN pip install ansible
RUN mkdir -p /etc/ansible
# emulate gui structure
RUN mkdir -p /home/root/Desktop
RUN mkdir -p /home/root/Downloads

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
